const taskCommands = {
    GET_ALL_TEACHERS: 'GET_ALL_TEACHERS',
    SAVE_TEACHER: 'SAVE_TEACHER',
    DELETE_TEACHER: 'DELETE_TEACHER',
    GET_ALL_TOPICS: 'GET_ALL_TOPICS',
    GET_COURSES_BY_TOPIC_ID: 'GET_COURSES_BY_TOPIC_ID',
    GET_DEFAULT_TOPIC: 'GET_DEFAULT_TOPIC',
    DELETE_TOPIC: 'DELETE_TOPIC',
    SAVE_TOPIC: 'SAVE_TOPIC',
    SAVE_COURSE_BY_TOPIC_ID: 'SAVE_COURSE_BY_TOPIC_ID',
    DELETE_COURSE_BY_TOPIC_ID: 'DELETE_COURSE_BY_TOPIC_ID',
};

export default taskCommands;
